export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;
export const INCREMENT_ENTHUSIASM_FINISH = 'INCREMENT_ENTHUSIASM_FINISH';
export type INCREMENT_ENTHUSIASM_FINISH = typeof INCREMENT_ENTHUSIASM_FINISH;